on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install tinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y curl libcurl4-doc libcurl4-openssl-dev
      - name: Install package dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr", "sessioninfo"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github(c("tlverse/sl3@devel"))
        shell: Rscript {0}

      - name: Check package
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--ignore-vignettes", build_args = "--no-build-vignettes", error_on = "error")
        shell: Rscript {0}

      - name: Upload code coverage
        if: runner.os == 'Linux'
        run: |
          covr::codecov(line_exclusions = list("R/plots.R", "R/print.R", "R/options.R"))
        shell: Rscript {0}
